version: '3.1'

services:

  db:
    container_name: workaround-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: todo_app_db
    ports:
      - 5433:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080

  app:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8082

  sample:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true